Repository Gdevelop-game/GDevelop-Open-Game, pull requests merged in 2020-06, with the labels that each got.

#15 Add auto executable build
  .github/workflows/main.yml
Labels: CI, enhancement

#12 Added settings
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
  src/versions/blue_button07.png
  src/versions/blue_button08.png
  src/versions/eventsFunctionsExtensions/backgroundscene.json
  src/versions/eventsFunctionsExtensions/roommanager.json
  src/versions/game.json
  src/versions/game.json.autosave
  src/versions/green_button00.png
  src/versions/green_button01.png
  src/versions/layouts/functionsincludes.json
  src/versions/layouts/intro.json
  src/versions/layouts/menu.json
  src/versions/layouts/overworld.json
  src/versions/layouts/rooms.json
  src/versions/layouts/settings.json
Labels: feature

#27 Add ammo to gun
  src/externalEvents/global.json
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement

#28 Merge all doors External Events
  src/externalEvents/doors.json
  src/externalEvents/east_doors.json
  src/externalEvents/north_doors.json
  src/externalEvents/south_doors.json
  src/externalEvents/west_doors.json
  src/game.json
  src/layouts/overworld.json
Labels: Refactor

#40 removed the external event json files that were not being used
  src/externalEvents/crossair.json
  src/externalEvents/fade.json
  src/externalEvents/south_doors.json
Labels: feature

#41 Seprated ammo per gun
  src/externalEvents/niko.json
  src/game.json
Labels: enhancement

#42 New gun
  src/externalEvents/niko.json
  src/flame thrower fire collision.png
  src/flame thrower place holder.png
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
  src/versions/ManBlue_flame thrower place holder.png
Labels: feature

#43 bug for flamethrower fixed
  src/externalEvents/niko.json
  src/game.json
Labels: Bug fix

#44 Refactor build system
  .github/workflows/main.yml
  build/.gitignore
  build/build.js
  build/package-lock.json
  build/package.json
Labels: CI

#45 add custom loading screen
  build/.gitignore
  build/build.js
  build/build_electron.js
  build/build_web.js
  build/customLoadingScreen/loadingscreen-pixi-renderer.js
  build/package.json
Labels: CI, enhancement, feature

#49 Add caching
  build/build.js
  build/customHtml/index.html
  build/workboxCache/sw.js
Labels: CI, enhancement, feature

#51 new gun(need zoom thign though)
  src/assets/gun_placeholder/manBlue_gun_place_holder.png
  src/assets/gun_placeholder/weapon_gun_place_holder.png
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: Almost ready, enhancement

#52 Add features to companion app
  companion-app/package.json
  companion-app/src/AppsManager/App.js
  companion-app/src/AppsManager/Apps/Hello.jsx
  companion-app/src/AppsManager/Apps/Maps.jsx
  companion-app/src/AppsManager/AppsLister.tsx
  companion-app/src/AppsManager/AppsManager.jsx
  companion-app/src/Main/Main.jsx
  companion-app/src/react-app-env.d.ts
  companion-app/tsconfig.json
  companion-app/webpack.config.js
  companion-app/yarn.lock
Labels: Companion App

#58 added a new room
  src/assets/Interior/furniture/bed/tile_105.png
  src/assets/Interior/furniture/bed/tile_106.png
  src/assets/Interior/furniture/bed/tile_107.png
  src/assets/Interior/furniture/bed/tile_48.png
  src/assets/Interior/furniture/bed/tile_51.png
  src/assets/Interior/furniture/bed/tile_52.png
  src/assets/Interior/furniture/bed/tile_53.png
  src/assets/Interior/furniture/bed/tile_75.png
  src/assets/Interior/furniture/bed/tile_78.png
  src/assets/Interior/furniture/bed/tile_79.png
  src/assets/Interior/furniture/bed/tile_80.png
  src/assets/Interior/furniture/table/tile_506.png
  src/assets/Interior/furniture/table/tile_507.png
  src/assets/Interior/furniture/table/tile_508.png
  src/assets/Interior/furniture/table/tile_509.png
  src/assets/Interior/furniture/table/tile_510.png
  src/assets/Road/sand/dirt.png
  src/eventsFunctionsExtensions/roommanager.json
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
  src/layouts/settings.json
Labels: feature

#61 Improve disconnection from Companion
  companion-app/src/Components/Connect.jsx
  companion-app/src/Main/Main.jsx
Labels: Companion App, enhancement

#63 rocket gaucher(weapon)
  src/assets/character/Player/manBlue_rocketlauncher.png
  src/assets/weapons/bullet/bulletYellow_outline_.png
  src/assets/weapons/gun/rocket_launcher.png
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: feature

#68 Tazer(mele weapon)
  src/assets/character/Player/manBlue_tazer.png
  src/assets/sprite_objects/tazer_Hitbox/tazer_hitbox=0.png
  src/assets/sprite_objects/tazer_Hitbox/tazer_hitbox=1.png
  src/assets/sprite_objects/tazer_Hitbox/tazer_hitbox=2.png
  src/assets/weapons/energy.png
  src/assets/weapons/mele/tazer.png
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: Almost ready, feature

#67 added a phone
  src/assets/character/Player/phone/phone_apps.png
  src/assets/character/Player/phone/phone_lock.png
  src/assets/character/Player/phone/phone_unlock.png
  src/assets/character/Player/phone/pointer_1.png
  src/assets/character/Player/phone/pointer_2.png
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
Labels: feature
