Repository Gdevelop-game/GDevelop-Open-Game, pull requests merged in 2020-07, with the labels that each got.

#70 BETTER TAZER and weapon wheel
  src/assets/character/Player/manBlue_one_hand_hold.png
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement, feature

#72 added phone apps page
  src/assets/character/Player/phone/phone_apps.png
  src/assets/character/Player/phone/phone_lock.png
  src/assets/character/Player/phone/phone_unlock.png
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
Labels: feature

#73 bug fixes for weapon wheel and flame thrower texture change
  src/assets/character/Player/flamethrowerplayer.png
  src/assets/character/Player/manBlue_flametrhower.png
  src/assets/weapons/gun/flamethrower.png
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement

#75 addedd new roof tops
  src/assets/rooftop/roof_10.png
  src/assets/rooftop/roof_11.png
  src/assets/rooftop/roof_7.png
  src/assets/rooftop/roof_8.png
  src/assets/rooftop/roof_9.png
  src/game.json
  src/layouts/overworld.json
Labels: feature

#79 added map edges
  src/assets/Road/map_edge/tile_1.png
  src/assets/Road/map_edge/tile_10.png
  src/assets/Road/map_edge/tile_11.png
  src/assets/Road/map_edge/tile_12.png
  src/assets/Road/map_edge/tile_13.png
  src/assets/Road/map_edge/tile_14.png
  src/assets/Road/map_edge/tile_2.png
  src/assets/Road/map_edge/tile_3.png
  src/assets/Road/map_edge/tile_4.png
  src/assets/Road/map_edge/tile_5.png
  src/assets/Road/map_edge/tile_6.png
  src/assets/Road/map_edge/tile_7.png
  src/assets/Road/map_edge/tile_8.png
  src/assets/Road/map_edge/tile_9.png
  src/assets/Road/road/tile_37-1.png
  src/assets/water/tile_73.png
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#78 set things on fire
  niko.json
  overworld.json
Labels: enhancement

#80 changes
  niko.json
  overworld.json
  src/assets/character/Player/manBlue_sniper.png
  src/assets/weapons/gun/sniper.png
  src/assets/weapons/gun/weapon_sniper.png
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: Bug fix

#83 added phone wifi and time
  src/assets/character/Player/manBlue_phone_0.png
  src/assets/character/Player/manBlue_phone_1.png
  src/assets/character/Player/phone/phone_apps.png
  src/assets/character/Player/phone/phone_battery.png
  src/assets/character/Player/phone/phone_lock.png
  src/assets/character/Player/phone/phone_unlock.png
  src/assets/character/Player/phone/wifi_0.png
  src/assets/character/Player/phone/wifi_1.png
  src/assets/character/Player/phone/wifi_2.png
  src/assets/character/Player/phone/wifi_3.png
  src/eventsFunctionsExtensions/timeformatter.json
  src/externalEvents/niko.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#82 weapons dont work if holding phone(feature)
  src/externalEvents/niko.json
  src/externalEvents/phone.json
Labels: enhancement

#84 added map 1 (incomplete)
  src/assets/Road/map_edge/tile_15.png
  src/assets/Road/map_edge/tile_16.png
  src/assets/Road/map_edge/tile_17.png
  src/assets/Road/map_edge/tile_18.png
  src/assets/Road/map_edge/tile_19.png
  src/assets/Road/map_edge/tile_20.png
  src/assets/Road/road/tile_63-1.png
  src/externalEvents/global.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement

#85 modified the map 1
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#86 fixed sidewalk z order
  src/layouts/overworld.json
Labels: enhancement

#87 modified map 1
  src/layouts/overworld.json
Labels: enhancement

#88 added swim variable
  src/assets/character/Player/manBlue_swim_0.png
  src/assets/character/Player/manBlue_swim_1.png
  src/assets/character/Player/manBlue_swim_2.png
  src/assets/character/Player/manBlue_swim_3.png
  src/assets/character/Player/manBlue_swim_4.png
  src/assets/character/Player/manBlue_swim_5.png
  src/assets/character/Player/manBlue_swim_6.png
  src/assets/character/Player/manBlue_swim_7.png
  src/externalEvents/doors.json
  src/externalEvents/niko.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: feature

#89 Update README.md
  README.md
Labels: enhancement

#90 fixed the bug with guns and water
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#91 Gem13
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#92 changed texture of gun1 and gun2
  src/assets/character/Player/Machine_gun_hold.png
  src/assets/character/Player/Single_pistol.png
  src/assets/character/Player/manBlue_gun.png
  src/assets/character/Player/manBlue_machine.png
  src/assets/weapons/gun/Machine_gun_item.png
  src/assets/weapons/gun/Single_pistol_item.png
  src/assets/weapons/gun/weapon_gun.png
  src/assets/weapons/gun/weapon_machine.png
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement

#94 Fixed Settings, Created Room 5
  src/externalEvents/global.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
  src/layouts/settings.json
Labels: feature

#95 fixed swiming on land bug
  src/assets/character/Player/phone/pointer_1.png
  src/assets/character/Player/phone/pointer_2.png
  src/eventsFunctionsExtensions/roommanager.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement

#98 new texture for rocket launcher
  src/assets/character/Player/Rocket_launcher_loaded.png
  src/assets/character/Player/Rocket_launcher_unloaded.png
  src/assets/weapons/gun/Rocket_launcher_item.png
  src/externalEvents/niko.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: enhancement

#105 add objects to bullet_obstacles list.
  src/layouts/overworld.json
Labels: feature

#104 Update rooms.json
  src/layouts/rooms.json
Labels: enhancement

#106 flamethrower now sets stuff on fire
  src/externalEvents/niko.json
  src/layouts/overworld.json
Labels: feature

#107 tried "make the fire spawn at the end of the collision" but collision mask is too big for good results
  src/externalEvents/niko.json
  src/layouts/overworld.json
Labels: enhancement

#109 added phone pointer
  src/externalEvents/niko.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#108 Little changes to flame thrower set things to fire
  src/externalEvents/niko.json
  src/game.json
  src/layouts/rooms.json
Labels: enhancement

#112 made more updates to phone
  src/assets/character/Player/phone/phone_apps.png
  src/externalEvents/global.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#113 added a working phone pointer
  src/externalEvents/phone.json
  src/layouts/overworld.json
Labels: enhancement

#119 Add anchor to UI
  src/game.json
  src/layouts/menu.json
  src/layouts/settings.json
Labels: enhancement

#123 added weapons icons
  src/assets/UI/weapon_icons/rocket_launcher_icon.png
  src/assets/UI/weapon_icons/sniper_icon.png
  src/assets/UI/weapon_icons/tazer_icon.png
  src/externalEvents/niko.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#124 added more controls to alert
  src/game.json
  src/layouts/menu.json
  src/layouts/overworld.json
Labels: enhancement

#125 deleted menu scene
  src/game.json
Labels: enhancement

#126 added more routes in map 1
  src/layouts/overworld.json
Labels: enhancement

#128 update
  src/layouts/overworld.json
Labels: enhancement

#129 fixed road
  src/layouts/overworld.json
Labels: enhancement

#132 added a better look to the cross air
  src/assets/character/Player/phone/phone_battery_0.png
  src/assets/character/Player/phone/phone_battery_1.png
  src/assets/character/Player/phone/phone_battery_2.png
  src/assets/character/Player/phone/phone_battery_3.png
  src/externalEvents/global.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#134 added more roads
  src/assets/sprite_objects/mouse_point-1.png
  src/externalEvents/global.json
  src/externalLayouts/sports.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement
