Repository Gdevelop-game/GDevelop-Open-Game, pull requests merged in 2020-10, with the labels that each got.

#153 added map
  src/game.json
  src/layouts/intro.json
  src/layouts/overworld.json
Labels: enhancement

#154 Phone management
  src/externalEvents/niko.json
  src/externalEvents/phone.json
  src/layouts/overworld.json
Labels: enhancement

#155 Added Screen Shake for Rocket launcher and Minor Phone Fix
  src/externalEvents/niko.json
Labels: enhancement, hacktoberfest

#157 added more side walk
  src/game.json
  src/layouts/overworld.json
Labels: Almost ready

#164 Update README
  README.md
Labels: documentation

#165 Added Contributors to the readme
  README.md
Labels: documentation

#161 Fixed Rooms
  src/layouts/overworld.json
  src/layouts/rooms.json
Labels: Bug fix

#168 Update gdexport
  build/package.json
Labels: CI, dependencies
