Repository Gdevelop-game/GDevelop-Open-Game, pull requests merged in 2020-12, with the labels that each got.

#176 Added Rooftops
  src/assets/rooftop/roof_14.png
  src/assets/rooftop/roof_14_horizontal.png
  src/assets/rooftop/roof_16.png
  src/assets/rooftop/roof_17.png
  src/assets/rooftop/roof_18.png
  src/assets/rooftop/roof_19.png
  src/assets/rooftop/roof_21.png
  src/assets/rooftop/roof_22.png
  src/assets/rooftop/roof_23.png
  src/assets/rooftop/roof_24.png
  src/assets/rooftop/roof_25.png
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#179 Update Player's phone
  src/assets/character/Player/phone/phone_app.png
  src/assets/character/Player/phone/phone_lock.png
  src/assets/character/Player/phone/phone_lock_1.png
  src/assets/character/Player/phone/phone_lock_2.png
  src/assets/character/Player/phone/phone_lock_3.png
  src/assets/character/Player/phone/phone_lock_4.png
  src/assets/character/Player/phone/phone_lock_5.png
  src/assets/character/Player/phone/phone_lock_6.png
  src/assets/character/Player/phone/phone_off.png
  src/assets/character/Player/phone/pointer.png
  src/assets/character/Player/phone/pointer_1.png
  src/assets/character/Player/phone/pointer_2.png
  src/assets/character/Player/phone/pointer_3.png
  src/assets/character/Player/phone/pointer_4.png
  src/assets/character/Player/phone/pointer_5.png
  src/assets/character/Player/phone/pointer_6.png
  src/assets/character/Player/phone/pointer_7.png
  src/assets/character/Player/phone/thumb.png
  src/assets/character/Player/phone/thumb_1.png
  src/eventsFunctionsExtensions/backgroundscene.json
  src/eventsFunctionsExtensions/bounce.json
  src/eventsFunctionsExtensions/button.json
  src/eventsFunctionsExtensions/debugmessages.json
  src/eventsFunctionsExtensions/fade.json
  src/eventsFunctionsExtensions/roommanager.json
  src/eventsFunctionsExtensions/timeformatter.json
  src/externalEvents/phone.json
  src/game.json
  src/layouts/overworld.json
Labels: enhancement

#183 Try fix auto build
  .github/workflows/main.yml
Labels: Bug fix

#182 Added shake extension
  src/eventsFunctionsExtensions/camerashaking.json
  src/externalEvents/niko.json
  src/game.json
Labels: enhancement

#184 Add ko-fi support button
  README.md
Labels: documentation

#177 Remove contributors field from the README
  README.md
Labels: documentation
