Repository Gdevelop-game/GDevelop-Open-Game, pull requests merged in 2021-02, with the labels that each got.

#190 Rework build pipeline
  build/build.js
  build/package.json
  build/pwa/sw-web.js
  build/pwa/sw.js
  build/yarn.lock
Labels: CI, Refactor

#191 Move to GDexport plugins
  .node-version
  build/build.js
  build/customLoadingScreen/loadingscreen-pixi-renderer.js
  build/gdexport.config.js
  build/icons/apple-icon-120.png
  build/icons/apple-icon-152.png
  build/icons/apple-icon-167.png
  build/icons/apple-icon-180.png
  build/icons/manifest-icon-192.png
  build/icons/manifest-icon-512.png
  build/package-lock.json
  build/package.json
  build/pwa/manifest.webmanifest
  build/pwa/sw.js
  build/yarn.lock
Labels: CI, Refactor

#188 Update player animation
  build/.gitignore
  src/assets/character/Player/Rocket_launcher_loaded.png
  src/assets/character/Player/Rocket_launcher_unloaded.png
  src/assets/character/Player/Single_pistol.png
  src/assets/character/Player/Single_revolver.png
  src/assets/character/Player/knife_a1.png
  src/assets/character/Player/knife_a2.png
  src/assets/character/Player/knife_a3.png
  src/assets/character/Player/knife_a4.png
  src/assets/character/Player/knife_a5.png
  src/assets/character/Player/manBlue_phone_0.png
  src/assets/character/Player/manBlue_phone_1.png
  src/assets/character/Player/manBlue_phone_2.png
  src/assets/character/Player/manBlue_rocketlauncher.png
  src/assets/character/Player/manBlue_stand.png
  src/assets/character/Player/manBlue_walk_1.png
  src/assets/character/Player/manBlue_walk_2.png
  src/assets/map/one.json
  src/assets/weapons/bullet/rocket_launcher_bullet.png
  src/assets/weapons/gun/Rocket_launcher_item - rocket out.png
  src/assets/weapons/gun/Rocket_launcher_item.png
  src/assets/weapons/gun/Single_pistol_item.png
  src/assets/weapons/gun/Single_revolver_item.png
  src/assets/weapons/mele/knife.png
  src/eventsFunctionsExtensions/backgroundscene.json
  src/eventsFunctionsExtensions/bounce.json
  src/eventsFunctionsExtensions/button.json
  src/eventsFunctionsExtensions/camerashaking.json
  src/eventsFunctionsExtensions/debugmessages.json
  src/eventsFunctionsExtensions/fade.json
  src/eventsFunctionsExtensions/roommanager.json
  src/eventsFunctionsExtensions/timeformatter.json
  src/game.json
  src/layouts/overworld.json
  svg/characters/characters.svg
Labels: enhancement

#192 Update actions
  .github/workflows/main.yml
  build/.gitignore
Labels: Bug fix, CI
