Repository Gdevelop-game/GDevelop-Open-Game, pull requests merged in 2021-05, with the labels that each got.

#195 OS generated files to gitignore
  .gitignore
  src/.gitignore
Labels: enhancement

#198 Fix autobuild
  build/package-lock.json
  build/package.json
Labels: Bug fix, CI

#194 update readme
  README.md
Labels: documentation
